/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mendixlabs.mendixgradleplugin

import java.io.File
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir
import java.io.IOException

/**
 * A simple functional test for the 'mxw.gradle.greeting' plugin.
 */
class MxwGradlePluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

    @Test fun `can run task`() {
        // Set up the test build
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id('mendixlabs.mendix-gradle-plugin')
            }
            
            mendix {
                mendixVersion = "0.0.0"
                mprFileName = "App.mpr"
            }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("mx")
        runner.withProjectDir(projectDir)
        try {
            runner.build()
        } catch (ex: Exception) {
            println(ex)
        }

        // Verify the result

//        assertTrue(result.output.contains("0.0.0"))
    }
}
