/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mxw.gradle

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class MxwGradlePlugin: Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.tasks.register("mxw") { task ->
            task.doLast {
                println("Hello from plugin 'mendix.gradle-plugin'")
            }
        }

        project.tasks.register("mxbuild") { task ->
            task.doLast {
                println("MxBuild placeholder")
            }
        }
    }
}
