/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package mxw.gradle

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'mxw.gradle.greeting' plugin.
 */
class MxwGradlePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.mendixlabs.gradle-plugin")

        // Verify the result
        assertNotNull(project.tasks.findByName("mxw"))
    }
}
